FROM nginx:alpine

RUN apk add gettext

WORKDIR /usr/src/app

ENV ENV production

ENV SERVICE_HOST 0.0.0.0
ENV SERVICE_PORT 9765

COPY ./scripts/nginx.conf.template /etc/nginx/nginx.conf.template
COPY . .

CMD ["./scripts/docker-start.sh"]
