FROM node:10-alpine

RUN apk add nginx gettext-base

WORKDIR /usr/src/app

ENV ENV production
ENV SERVICE_PORT 9765

COPY ./scripts/nginx.conf.template /etc/nginx/nginx.conf.template
COPY . .

CMD ["./scripts/docker-start.sh"]
