version: "3.4"
services:
  test:
    container_name: karmen_backend_test
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      FLASK_APP: server
      POSTGRES_PASSWORD: print3dtest
      POSTGRES_USER: print3dtest
      POSTGRES_DB: print3dtest
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 54350
      REDIS_HOST: localhost
      REDIS_PORT: 6380
      CELERY_CONFIG: '{}'
      SECRET_KEY: tests
    depends_on:
      - redis
      - dbmigrations
  dbmigrations:
    container_name: karmen_backend_dbmigrations_test
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      POSTGRES_PASSWORD: print3dtest
      POSTGRES_USER: print3dtest
      POSTGRES_DB: print3dtest
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 54350
    command: scripts/migrate.sh
    depends_on:
      - postgres
  redis:
    container_name: karmen_backend_redis_test
    image: redis:5
    ports:
      - 6380:6379
  postgres:
    container_name: karmen_backend_pg_test
    image: postgres:11
    environment:
      POSTGRES_DB: print3dtest
      POSTGRES_PASSWORD: print3dtest
      POSTGRES_USER: print3dtest
    ports:
      - 54350:5432