FROM python:3.6-buster
RUN apt-get update && apt-get upgrade --yes && apt-get install --yes git make g++ libpq-dev avahi-utils arp-scan nginx build-essential
RUN pip install --upgrade pip
RUN pip install pipenv

WORKDIR /usr/src/app

COPY Pipfile* ./
RUN pipenv lock --requirements > requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["make", "flask"]

EXPOSE 5000
