; generated by PrusaSlicer 2.0.0+linux64 on 2019-09-25 at 13:08:24

; 

M73 Q0 S3
M201 X1000 Y1000 Z1000 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E1.50 ; sets the jerk limits, mm/sec
; filament used [mm] = 94.7
; filament used [cm3] = 0.2
; filament used [g] = 0.3
; filament cost = 0.0
; total filament used [g] = 0.3
; total filament cost = 0.0
; estimated printing time (normal mode) = 3m 13s
; estimated printing time (silent mode) = 3m 14s

M204 S1250
G1 F961
G1 X133.970 Y110.786 E0.05716
G1 X133.926 Y111.001 E0.00673
G1 X133.924 Y111.355 E0.01085

; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_speed = 20
; first_layer_temperature = 215
; gcode_comments = 0
; gcode_flavor = marlin
; temperature = 215
; bed_temperature = 60
